version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: 1.19.2
      GENERIC_PACK: /modpacks/decorations.zip
      USEMODPACK_START_SCRIPT: "false"
      MEMORY: "4G"

    ports:
      - 25565:25565
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro

  backup:
    image: alpine    
    tty: false
    environment:
      - TARGET=data
    volumes:
      - ./backup:/backup
      - data:/volume
    command: sh -c "tar -cjf /backup/$${TARGET}-`date +%Y%m%d%H%M%S`.tar.bz2 -C /volume ./"

volumes:
  data:
